from pathlib import Path


html = '''<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Personal performance lab</title><style>
:root{--ink:#17212b;--muted:#68737d;--line:#dce4e7;--paper:#f5f7f7;--teal:#16866e;--orange:#df7950}*{box-sizing:border-box}body{margin:0;background:var(--paper);color:var(--ink);font:15px/1.5 -apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif}main{max-width:960px;margin:auto;padding:56px 20px}header{max-width:680px;margin-bottom:30px}.eyebrow{color:var(--orange);font-size:12px;font-weight:800;letter-spacing:.15em;text-transform:uppercase}h1{font-size:clamp(34px,7vw,68px);line-height:.98;margin:8px 0 16px}p{color:var(--muted)}.choices{display:grid;grid-template-columns:1fr 1fr;gap:16px}.choice{display:block;text-decoration:none;color:inherit;background:white;border:1px solid var(--line);border-radius:12px;padding:24px;min-height:220px;transition:transform .2s,border-color .2s,box-shadow .2s}.choice:hover{transform:translateY(-3px);border-color:var(--teal);box-shadow:0 12px 30px #17212b12}.icon{font-size:30px;margin-bottom:28px}.choice h2{margin:0 0 8px;font-size:23px}.choice p{margin:0 0 22px}.open{color:var(--teal);font-weight:800;font-size:13px}@media(max-width:650px){main{padding:34px 14px}.choices{grid-template-columns:1fr}.choice{min-height:180px}}
</style></head><body><main><header><div class="eyebrow">Personal performance lab</div><h1>Your data, two ways.</h1><p>Choose the view you want. Run analysis explains the effort. Recovery, strain and sleep explain the day around it.</p></header><section class="choices"><a class="choice" href="run-analysis.html"><div class="icon">↗</div><h2>Run analysis</h2><p>Detailed activity charts, pace, heart rate, splits, zones and cross-run evidence.</p><span class="open">Open run analysis →</span></a><a class="choice" href="recovery.html"><div class="icon">◒</div><h2>Recovery lab</h2><p>Recovery score, daily strain and sleep need built from your own Garmin baselines.</p><span class="open">Open recovery lab →</span></a></section></main></body></html>'''
Path("index.html").write_text(html)
print("Generated index.html home page")
